Add Redux
nbagramov/money-waste-react pull request #3
Opened 2021-09-15 11:11 UTC by nbagramov

2021-09-16 11:25 UTC, IslamRustam requested changes

2021-09-16 11:25 UTC, IslamRustam commented on src/store/reducer.ts
> +      return [...newPurchaseList];
if purchaseIndex **!==** -1 
You shouldn't call `return [...newPurchaseList]` if purchaseIndex === -1. In this case you should just call `return state;`

2021-09-16 11:25 UTC, IslamRustam commented on src/store/reducer.ts
> +      return [...changePlacePurchaseList];
same as above

2021-09-16 11:25 UTC, IslamRustam commented on src/store/reducer.ts
> +      return [...newPurchaseList];
same as above

2021-09-16 11:25 UTC, IslamRustam commented on src/store/reducer.ts
> +      return [...newPurchaseList];
and you should really have a reason to use not strict comparison (==) instead of strict comparison (===)

2021-09-20 09:56 UTC, IslamRustamov1 requested changes

2021-09-20 09:56 UTC, IslamRustamov1 commented on src/store/reducer.ts
> +      };
Why do you recreate purchases list? Just error: true is enought

2021-09-20 09:56 UTC, IslamRustamov1 commented on src/store/reducer.ts
> +    }
same as above

2021-09-20 09:56 UTC, IslamRustamov1 commented on src/store/reducer.ts
> +      };
same as above

2021-09-20 09:56 UTC, IslamRustamov1 commented on src/store/reducer.ts
> +      };
same as above

2021-09-20 11:03 UTC, merged